/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalCoinsInCirculation' : Coins,
  'totalApprovedWithdrawalsRupees' : bigint,
  'pendingWithdrawalsCount' : bigint,
  'totalUsers' : bigint,
}
export interface AnnouncementPublic {
  'id' : bigint,
  'title' : string,
  'expiresAt' : [] | [Timestamp],
  'urgency' : AnnouncementUrgency,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'isActive' : boolean,
  'target' : AnnouncementTarget,
  'message' : string,
  'scheduledAt' : [] | [Timestamp],
}
export type AnnouncementTarget = { 'all' : null } |
  { 'adminsOnly' : null } |
  { 'newUsers' : null } |
  { 'inactiveUsers' : null };
export type AnnouncementUrgency = { 'warning' : null } |
  { 'info' : null } |
  { 'urgent' : null };
export interface AppSettings {
  'dailyBaseReward' : bigint,
  'referralsEnabled' : boolean,
  'tasksEnabled' : boolean,
  'dailyCoinsGrantCap' : bigint,
  'modifiedBy' : [] | [UserId],
  'adsEnabled' : boolean,
  'maxDailyAdWatches' : bigint,
  'dailyRewardsEnabled' : boolean,
  'maxCoinsPerUser' : bigint,
  'coinsPerAd' : bigint,
  'lastModified' : Timestamp,
  'streakCap' : bigint,
  'fraudPenaltyCoins' : bigint,
  'withdrawalsEnabled' : boolean,
  'referralBonus' : bigint,
  'streakMultiplier' : bigint,
  'minWithdrawalRupees' : bigint,
}
export interface BlockAuditEntry {
  'blocked' : boolean,
  'timestamp' : Timestamp,
  'adminId' : UserId,
  'reason' : string,
}
export type Coins = bigint;
export interface DailyEarningEntry {
  'date' : string,
  'rupeesWithdrawn' : bigint,
  'coinsEarned' : bigint,
}
export interface EarningsBreakdown {
  'fromAds' : bigint,
  'fromDaily' : bigint,
  'fromReferral' : bigint,
  'fromTasks' : bigint,
  'fromAdmin' : bigint,
}
export interface EnhancedAdminStats {
  'avgCoinsPerAd' : bigint,
  'totalCoinsInCirculation' : Coins,
  'earningsBreakdown' : EarningsBreakdown,
  'totalApprovedWithdrawalsRupees' : bigint,
  'pendingWithdrawalsCount' : bigint,
  'activeUsersThisWeek' : bigint,
  'dailyEarningsTrend' : Array<DailyEarningEntry>,
  'totalAdsWatched' : bigint,
  'totalUsers' : bigint,
  'totalCoinsEarned' : bigint,
  'totalRupeesPaidOut' : bigint,
}
export interface FraudFlagPublic {
  'userId' : UserId,
  'resolution' : [] | [FraudResolution],
  'isResolved' : boolean,
  'evidence' : string,
  'flagType' : FraudFlagType,
  'flaggedAt' : Timestamp,
  'resolvedAt' : [] | [Timestamp],
  'resolvedBy' : [] | [UserId],
  'reason' : string,
}
export type FraudFlagType = { 'suspiciousReferral' : null } |
  { 'suspiciousAdClicks' : null } |
  { 'referralLoop' : null } |
  { 'manualFlag' : null } |
  { 'multipleAccounts' : null } |
  { 'earlyWithdrawal' : null };
export type FraudResolution = { 'blockUser' : null } |
  { 'dismiss' : null } |
  { 'markLegitimate' : null };
export interface FraudStats {
  'mostCommonFlagType' : string,
  'unresolvedFlags' : bigint,
  'totalFlagged' : bigint,
  'totalCoinsRolledBack' : bigint,
  'resolvedFlags' : bigint,
}
export interface LeaderboardEntry {
  'username' : string,
  'userId' : string,
  'rank' : bigint,
  'coinsEarned' : bigint,
}
export interface LeaderboardResult {
  'userRank' : { 'username' : string, 'rank' : bigint, 'coinsEarned' : bigint },
  'entries' : Array<LeaderboardEntry>,
}
export interface ReferralRelationshipPublic {
  'status' : ReferralStatus,
  'refereeId' : UserId,
  'referrerId' : UserId,
  'timestamp' : Timestamp,
  'revokeReason' : [] | [string],
  'bonusGiven' : Coins,
}
export type ReferralStatus = { 'active' : null } |
  { 'revoked' : null } |
  { 'flagged' : null };
export interface SettingsChangeLog {
  'field' : string,
  'newVal' : string,
  'timestamp' : Timestamp,
  'adminId' : UserId,
  'oldVal' : string,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'coinReward' : Coins,
  'isActive' : boolean,
}
export interface TaskCompletion {
  'completedAt' : Timestamp,
  'userId' : UserId,
  'taskId' : bigint,
}
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'method' : TransactionMethod,
  'userId' : UserId,
  'note' : string,
  'createdAt' : Timestamp,
  'isCredit' : boolean,
  'amount' : Coins,
}
export type TransactionMethod = { 'ad' : null } |
  { 'referral' : null } |
  { 'admin' : null } |
  { 'task' : null } |
  { 'withdrawal' : null } |
  { 'daily' : null };
export interface UserAdminDetail {
  'totalWithdrawnRupees' : bigint,
  'fraudFlagCount' : bigint,
  'totalCoinsEarned' : Coins,
  'profile' : UserProfilePublic,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'lastLoginDate' : Timestamp,
  'principal' : UserId,
  'referralCode' : string,
  'username' : string,
  'coinBalance' : Coins,
  'isBlocked' : boolean,
  'createdAt' : Timestamp,
  'mobileNumber' : [] | [string],
  'mobileVerified' : boolean,
  'referredBy' : [] | [UserId],
  'blockHistory' : Array<BlockAuditEntry>,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WithdrawalMethod = { 'upi' : null } |
  { 'bank' : null } |
  { 'paytm' : null };
export interface WithdrawalRequestPublic {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'method' : WithdrawalMethod,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentDetails' : [] | [string],
  'adminNote' : string,
  'rupeeAmount' : bigint,
  'details' : string,
  'paidAt' : [] | [Timestamp],
  'coinsDeducted' : Coins,
  'resolvedAt' : [] | [Timestamp],
  'resolvedBy' : [] | [UserId],
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminAddCoins' : ActorMethod<[UserId, Coins, string], undefined>,
  'adminAddWithdrawalNote' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveWithdrawal' : ActorMethod<[bigint, string], undefined>,
  'adminBulkApproveWithdrawals' : ActorMethod<
    [Array<bigint>, string],
    { 'failed' : bigint, 'succeeded' : bigint }
  >,
  'adminBulkBlockUsers' : ActorMethod<
    [Array<UserId>, boolean, string],
    { 'failed' : bigint, 'succeeded' : bigint }
  >,
  'adminBulkRejectWithdrawals' : ActorMethod<
    [Array<bigint>, string],
    { 'failed' : bigint, 'succeeded' : bigint }
  >,
  'adminCreateAnnouncement' : ActorMethod<
    [
      string,
      string,
      AnnouncementUrgency,
      AnnouncementTarget,
      [] | [Timestamp],
      [] | [Timestamp],
    ],
    bigint
  >,
  'adminDeductCoins' : ActorMethod<[UserId, Coins, string], undefined>,
  'adminDeleteAnnouncement' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDetectSuspiciousReferralsByTime' : ActorMethod<
    [],
    Array<ReferralRelationshipPublic>
  >,
  'adminFlagUser' : ActorMethod<
    [UserId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllReferrals' : ActorMethod<[], Array<ReferralRelationshipPublic>>,
  'adminGetAllTransactions' : ActorMethod<
    [
      [] | [UserId],
      [] | [TransactionMethod],
      [] | [Timestamp],
      [] | [Timestamp],
      bigint,
      bigint,
    ],
    { 'total' : bigint, 'transactions' : Array<Transaction> }
  >,
  'adminGetAllUsers' : ActorMethod<[], Array<UserAdminDetail>>,
  'adminGetAllWithdrawals' : ActorMethod<
    [
      [] | [WithdrawalStatus],
      [] | [UserId],
      [] | [Timestamp],
      [] | [Timestamp],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<WithdrawalRequestPublic>
  >,
  'adminGetEnhancedStats' : ActorMethod<[], EnhancedAdminStats>,
  'adminGetFlaggedUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'adminGetFraudFlags' : ActorMethod<[boolean], Array<FraudFlagPublic>>,
  'adminGetFraudStats' : ActorMethod<[], FraudStats>,
  'adminGetSettings' : ActorMethod<[], AppSettings>,
  'adminGetSettingsChangeLog' : ActorMethod<[], Array<SettingsChangeLog>>,
  'adminGetStats' : ActorMethod<[], AdminStats>,
  'adminGetUserDetail' : ActorMethod<[UserId], [] | [UserAdminDetail]>,
  'adminGetUserReferralChain' : ActorMethod<
    [UserId],
    {
      'referred' : Array<UserProfilePublic>,
      'referredBy' : [] | [UserProfilePublic],
    }
  >,
  'adminListAnnouncements' : ActorMethod<[], Array<AnnouncementPublic>>,
  'adminMarkWithdrawalPaid' : ActorMethod<[bigint, string], undefined>,
  'adminRejectWithdrawal' : ActorMethod<[bigint, string], undefined>,
  'adminResolveFraudFlag' : ActorMethod<
    [UserId, FraudFlagType, FraudResolution],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRevokeReferral' : ActorMethod<
    [UserId, UserId, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminToggleBlock' : ActorMethod<[UserId, boolean, string], undefined>,
  'adminUpdateAnnouncement' : ActorMethod<
    [
      bigint,
      string,
      string,
      AnnouncementUrgency,
      AnnouncementTarget,
      [] | [Timestamp],
      [] | [Timestamp],
      boolean,
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateSettings' : ActorMethod<
    [AppSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'applyReferralCode' : ActorMethod<[string, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyReward' : ActorMethod<[[] | [string]], Coins>,
  'completeTask' : ActorMethod<[bigint, [] | [string]], Coins>,
  'dismissAnnouncement' : ActorMethod<
    [bigint, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getActiveAnnouncements' : ActorMethod<
    [[] | [string]],
    Array<AnnouncementPublic>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[[] | [string]], Coins>,
  'getMyCompletedTasks' : ActorMethod<[[] | [string]], Array<TaskCompletion>>,
  'getMyMobileStatus' : ActorMethod<
    [[] | [string]],
    { 'mobileNumber' : [] | [string], 'mobileVerified' : boolean }
  >,
  'getMyProfile' : ActorMethod<[[] | [string]], [] | [UserProfilePublic]>,
  'getMyReferralCode' : ActorMethod<[[] | [string]], string>,
  'getMyWithdrawals' : ActorMethod<
    [[] | [string]],
    Array<WithdrawalRequestPublic>
  >,
  'getRupeeBalance' : ActorMethod<[[] | [string]], bigint>,
  'getSessionPrincipal' : ActorMethod<[string], [] | [UserId]>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getTopEarners' : ActorMethod<
    [string, bigint, [] | [string]],
    LeaderboardResult
  >,
  'getTransactionHistory' : ActorMethod<
    [bigint, bigint, [] | [string]],
    { 'total' : bigint, 'transactions' : Array<Transaction> }
  >,
  'getUserProfile' : ActorMethod<
    [UserId, [] | [string]],
    [] | [UserProfilePublic]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTasks' : ActorMethod<[], Array<Task>>,
  'loginWithMobileOTP' : ActorMethod<
    [string, string],
    { 'ok' : { 'isNewUser' : boolean, 'sessionToken' : string } } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<[string, [] | [string]], UserProfilePublic>,
  'requestMobileOTP' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitWithdrawal' : ActorMethod<
    [WithdrawalMethod, string, bigint, [] | [string], [] | [string]],
    WithdrawalRequestPublic
  >,
  'verifyMobileOTP' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'watchAd' : ActorMethod<[[] | [string]], Coins>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];