/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Coins = IDL.Nat;
export const AnnouncementUrgency = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'urgent' : IDL.Null,
});
export const AnnouncementTarget = IDL.Variant({
  'all' : IDL.Null,
  'adminsOnly' : IDL.Null,
  'newUsers' : IDL.Null,
  'inactiveUsers' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ReferralStatus = IDL.Variant({
  'active' : IDL.Null,
  'revoked' : IDL.Null,
  'flagged' : IDL.Null,
});
export const ReferralRelationshipPublic = IDL.Record({
  'status' : ReferralStatus,
  'refereeId' : UserId,
  'referrerId' : UserId,
  'timestamp' : Timestamp,
  'revokeReason' : IDL.Opt(IDL.Text),
  'bonusGiven' : Coins,
});
export const TransactionMethod = IDL.Variant({
  'ad' : IDL.Null,
  'referral' : IDL.Null,
  'admin' : IDL.Null,
  'task' : IDL.Null,
  'withdrawal' : IDL.Null,
  'daily' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'method' : TransactionMethod,
  'userId' : UserId,
  'note' : IDL.Text,
  'createdAt' : Timestamp,
  'isCredit' : IDL.Bool,
  'amount' : Coins,
});
export const BlockAuditEntry = IDL.Record({
  'blocked' : IDL.Bool,
  'timestamp' : Timestamp,
  'adminId' : UserId,
  'reason' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'lastLoginDate' : Timestamp,
  'principal' : UserId,
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'coinBalance' : Coins,
  'isBlocked' : IDL.Bool,
  'createdAt' : Timestamp,
  'mobileNumber' : IDL.Opt(IDL.Text),
  'mobileVerified' : IDL.Bool,
  'referredBy' : IDL.Opt(UserId),
  'blockHistory' : IDL.Vec(BlockAuditEntry),
  'currentStreak' : IDL.Nat,
});
export const UserAdminDetail = IDL.Record({
  'totalWithdrawnRupees' : IDL.Nat,
  'fraudFlagCount' : IDL.Nat,
  'totalCoinsEarned' : Coins,
  'profile' : UserProfilePublic,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalMethod = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
  'paytm' : IDL.Null,
});
export const WithdrawalRequestPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'method' : WithdrawalMethod,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentDetails' : IDL.Opt(IDL.Text),
  'adminNote' : IDL.Text,
  'rupeeAmount' : IDL.Nat,
  'details' : IDL.Text,
  'paidAt' : IDL.Opt(Timestamp),
  'coinsDeducted' : Coins,
  'resolvedAt' : IDL.Opt(Timestamp),
  'resolvedBy' : IDL.Opt(UserId),
});
export const EarningsBreakdown = IDL.Record({
  'fromAds' : IDL.Nat,
  'fromDaily' : IDL.Nat,
  'fromReferral' : IDL.Nat,
  'fromTasks' : IDL.Nat,
  'fromAdmin' : IDL.Nat,
});
export const DailyEarningEntry = IDL.Record({
  'date' : IDL.Text,
  'rupeesWithdrawn' : IDL.Nat,
  'coinsEarned' : IDL.Nat,
});
export const EnhancedAdminStats = IDL.Record({
  'avgCoinsPerAd' : IDL.Nat,
  'totalCoinsInCirculation' : Coins,
  'earningsBreakdown' : EarningsBreakdown,
  'totalApprovedWithdrawalsRupees' : IDL.Nat,
  'pendingWithdrawalsCount' : IDL.Nat,
  'activeUsersThisWeek' : IDL.Nat,
  'dailyEarningsTrend' : IDL.Vec(DailyEarningEntry),
  'totalAdsWatched' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalCoinsEarned' : IDL.Nat,
  'totalRupeesPaidOut' : IDL.Nat,
});
export const FraudResolution = IDL.Variant({
  'blockUser' : IDL.Null,
  'dismiss' : IDL.Null,
  'markLegitimate' : IDL.Null,
});
export const FraudFlagType = IDL.Variant({
  'suspiciousReferral' : IDL.Null,
  'suspiciousAdClicks' : IDL.Null,
  'referralLoop' : IDL.Null,
  'manualFlag' : IDL.Null,
  'multipleAccounts' : IDL.Null,
  'earlyWithdrawal' : IDL.Null,
});
export const FraudFlagPublic = IDL.Record({
  'userId' : UserId,
  'resolution' : IDL.Opt(FraudResolution),
  'isResolved' : IDL.Bool,
  'evidence' : IDL.Text,
  'flagType' : FraudFlagType,
  'flaggedAt' : Timestamp,
  'resolvedAt' : IDL.Opt(Timestamp),
  'resolvedBy' : IDL.Opt(UserId),
  'reason' : IDL.Text,
});
export const FraudStats = IDL.Record({
  'mostCommonFlagType' : IDL.Text,
  'unresolvedFlags' : IDL.Nat,
  'totalFlagged' : IDL.Nat,
  'totalCoinsRolledBack' : IDL.Nat,
  'resolvedFlags' : IDL.Nat,
});
export const AppSettings = IDL.Record({
  'dailyBaseReward' : IDL.Nat,
  'referralsEnabled' : IDL.Bool,
  'tasksEnabled' : IDL.Bool,
  'dailyCoinsGrantCap' : IDL.Nat,
  'modifiedBy' : IDL.Opt(UserId),
  'adsEnabled' : IDL.Bool,
  'maxDailyAdWatches' : IDL.Nat,
  'dailyRewardsEnabled' : IDL.Bool,
  'maxCoinsPerUser' : IDL.Nat,
  'coinsPerAd' : IDL.Nat,
  'lastModified' : Timestamp,
  'streakCap' : IDL.Nat,
  'fraudPenaltyCoins' : IDL.Nat,
  'withdrawalsEnabled' : IDL.Bool,
  'referralBonus' : IDL.Nat,
  'streakMultiplier' : IDL.Nat,
  'minWithdrawalRupees' : IDL.Nat,
});
export const SettingsChangeLog = IDL.Record({
  'field' : IDL.Text,
  'newVal' : IDL.Text,
  'timestamp' : Timestamp,
  'adminId' : UserId,
  'oldVal' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalCoinsInCirculation' : Coins,
  'totalApprovedWithdrawalsRupees' : IDL.Nat,
  'pendingWithdrawalsCount' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const AnnouncementPublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'expiresAt' : IDL.Opt(Timestamp),
  'urgency' : AnnouncementUrgency,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'isActive' : IDL.Bool,
  'target' : AnnouncementTarget,
  'message' : IDL.Text,
  'scheduledAt' : IDL.Opt(Timestamp),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskCompletion = IDL.Record({
  'completedAt' : Timestamp,
  'userId' : UserId,
  'taskId' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Text,
  'rank' : IDL.Nat,
  'coinsEarned' : IDL.Nat,
});
export const LeaderboardResult = IDL.Record({
  'userRank' : IDL.Record({
    'username' : IDL.Text,
    'rank' : IDL.Nat,
    'coinsEarned' : IDL.Nat,
  }),
  'entries' : IDL.Vec(LeaderboardEntry),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'coinReward' : Coins,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminAddCoins' : IDL.Func([UserId, Coins, IDL.Text], [], []),
  'adminAddWithdrawalNote' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminBulkApproveWithdrawals' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
      [],
    ),
  'adminBulkBlockUsers' : IDL.Func(
      [IDL.Vec(UserId), IDL.Bool, IDL.Text],
      [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
      [],
    ),
  'adminBulkRejectWithdrawals' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
      [],
    ),
  'adminCreateAnnouncement' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        AnnouncementUrgency,
        AnnouncementTarget,
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
      ],
      [IDL.Nat],
      [],
    ),
  'adminDeductCoins' : IDL.Func([UserId, Coins, IDL.Text], [], []),
  'adminDeleteAnnouncement' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDetectSuspiciousReferralsByTime' : IDL.Func(
      [],
      [IDL.Vec(ReferralRelationshipPublic)],
      ['query'],
    ),
  'adminFlagUser' : IDL.Func(
      [UserId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllReferrals' : IDL.Func(
      [],
      [IDL.Vec(ReferralRelationshipPublic)],
      ['query'],
    ),
  'adminGetAllTransactions' : IDL.Func(
      [
        IDL.Opt(UserId),
        IDL.Opt(TransactionMethod),
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        IDL.Nat,
        IDL.Nat,
      ],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'transactions' : IDL.Vec(Transaction),
        }),
      ],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserAdminDetail)], ['query']),
  'adminGetAllWithdrawals' : IDL.Func(
      [
        IDL.Opt(WithdrawalStatus),
        IDL.Opt(UserId),
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(WithdrawalRequestPublic)],
      ['query'],
    ),
  'adminGetEnhancedStats' : IDL.Func([], [EnhancedAdminStats], ['query']),
  'adminGetFlaggedUsers' : IDL.Func(
      [],
      [IDL.Vec(UserProfilePublic)],
      ['query'],
    ),
  'adminGetFraudFlags' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(FraudFlagPublic)],
      ['query'],
    ),
  'adminGetFraudStats' : IDL.Func([], [FraudStats], ['query']),
  'adminGetSettings' : IDL.Func([], [AppSettings], ['query']),
  'adminGetSettingsChangeLog' : IDL.Func(
      [],
      [IDL.Vec(SettingsChangeLog)],
      ['query'],
    ),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'adminGetUserDetail' : IDL.Func(
      [UserId],
      [IDL.Opt(UserAdminDetail)],
      ['query'],
    ),
  'adminGetUserReferralChain' : IDL.Func(
      [UserId],
      [
        IDL.Record({
          'referred' : IDL.Vec(UserProfilePublic),
          'referredBy' : IDL.Opt(UserProfilePublic),
        }),
      ],
      ['query'],
    ),
  'adminListAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(AnnouncementPublic)],
      ['query'],
    ),
  'adminMarkWithdrawalPaid' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminRejectWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminResolveFraudFlag' : IDL.Func(
      [UserId, FraudFlagType, FraudResolution],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRevokeReferral' : IDL.Func(
      [UserId, UserId, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminToggleBlock' : IDL.Func([UserId, IDL.Bool, IDL.Text], [], []),
  'adminUpdateAnnouncement' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        AnnouncementUrgency,
        AnnouncementTarget,
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateSettings' : IDL.Func(
      [AppSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'applyReferralCode' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyReward' : IDL.Func([IDL.Opt(IDL.Text)], [Coins], []),
  'completeTask' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [Coins], []),
  'dismissAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveAnnouncements' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(AnnouncementPublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([IDL.Opt(IDL.Text)], [Coins], ['query']),
  'getMyCompletedTasks' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(TaskCompletion)],
      ['query'],
    ),
  'getMyMobileStatus' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'mobileNumber' : IDL.Opt(IDL.Text),
          'mobileVerified' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getMyProfile' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getMyReferralCode' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
  'getMyWithdrawals' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(WithdrawalRequestPublic)],
      ['query'],
    ),
  'getRupeeBalance' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Nat], ['query']),
  'getSessionPrincipal' : IDL.Func([IDL.Text], [IDL.Opt(UserId)], ['query']),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getTopEarners' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [LeaderboardResult],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'transactions' : IDL.Vec(Transaction),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [UserId, IDL.Opt(IDL.Text)],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'loginWithMobileOTP' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'isNewUser' : IDL.Bool,
            'sessionToken' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [UserProfilePublic],
      [],
    ),
  'requestMobileOTP' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitWithdrawal' : IDL.Func(
      [
        WithdrawalMethod,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [WithdrawalRequestPublic],
      [],
    ),
  'verifyMobileOTP' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'watchAd' : IDL.Func([IDL.Opt(IDL.Text)], [Coins], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Coins = IDL.Nat;
  const AnnouncementUrgency = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const AnnouncementTarget = IDL.Variant({
    'all' : IDL.Null,
    'adminsOnly' : IDL.Null,
    'newUsers' : IDL.Null,
    'inactiveUsers' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ReferralStatus = IDL.Variant({
    'active' : IDL.Null,
    'revoked' : IDL.Null,
    'flagged' : IDL.Null,
  });
  const ReferralRelationshipPublic = IDL.Record({
    'status' : ReferralStatus,
    'refereeId' : UserId,
    'referrerId' : UserId,
    'timestamp' : Timestamp,
    'revokeReason' : IDL.Opt(IDL.Text),
    'bonusGiven' : Coins,
  });
  const TransactionMethod = IDL.Variant({
    'ad' : IDL.Null,
    'referral' : IDL.Null,
    'admin' : IDL.Null,
    'task' : IDL.Null,
    'withdrawal' : IDL.Null,
    'daily' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'method' : TransactionMethod,
    'userId' : UserId,
    'note' : IDL.Text,
    'createdAt' : Timestamp,
    'isCredit' : IDL.Bool,
    'amount' : Coins,
  });
  const BlockAuditEntry = IDL.Record({
    'blocked' : IDL.Bool,
    'timestamp' : Timestamp,
    'adminId' : UserId,
    'reason' : IDL.Text,
  });
  const UserProfilePublic = IDL.Record({
    'lastLoginDate' : Timestamp,
    'principal' : UserId,
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'coinBalance' : Coins,
    'isBlocked' : IDL.Bool,
    'createdAt' : Timestamp,
    'mobileNumber' : IDL.Opt(IDL.Text),
    'mobileVerified' : IDL.Bool,
    'referredBy' : IDL.Opt(UserId),
    'blockHistory' : IDL.Vec(BlockAuditEntry),
    'currentStreak' : IDL.Nat,
  });
  const UserAdminDetail = IDL.Record({
    'totalWithdrawnRupees' : IDL.Nat,
    'fraudFlagCount' : IDL.Nat,
    'totalCoinsEarned' : Coins,
    'profile' : UserProfilePublic,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalMethod = IDL.Variant({
    'upi' : IDL.Null,
    'bank' : IDL.Null,
    'paytm' : IDL.Null,
  });
  const WithdrawalRequestPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'method' : WithdrawalMethod,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'paymentDetails' : IDL.Opt(IDL.Text),
    'adminNote' : IDL.Text,
    'rupeeAmount' : IDL.Nat,
    'details' : IDL.Text,
    'paidAt' : IDL.Opt(Timestamp),
    'coinsDeducted' : Coins,
    'resolvedAt' : IDL.Opt(Timestamp),
    'resolvedBy' : IDL.Opt(UserId),
  });
  const EarningsBreakdown = IDL.Record({
    'fromAds' : IDL.Nat,
    'fromDaily' : IDL.Nat,
    'fromReferral' : IDL.Nat,
    'fromTasks' : IDL.Nat,
    'fromAdmin' : IDL.Nat,
  });
  const DailyEarningEntry = IDL.Record({
    'date' : IDL.Text,
    'rupeesWithdrawn' : IDL.Nat,
    'coinsEarned' : IDL.Nat,
  });
  const EnhancedAdminStats = IDL.Record({
    'avgCoinsPerAd' : IDL.Nat,
    'totalCoinsInCirculation' : Coins,
    'earningsBreakdown' : EarningsBreakdown,
    'totalApprovedWithdrawalsRupees' : IDL.Nat,
    'pendingWithdrawalsCount' : IDL.Nat,
    'activeUsersThisWeek' : IDL.Nat,
    'dailyEarningsTrend' : IDL.Vec(DailyEarningEntry),
    'totalAdsWatched' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalCoinsEarned' : IDL.Nat,
    'totalRupeesPaidOut' : IDL.Nat,
  });
  const FraudResolution = IDL.Variant({
    'blockUser' : IDL.Null,
    'dismiss' : IDL.Null,
    'markLegitimate' : IDL.Null,
  });
  const FraudFlagType = IDL.Variant({
    'suspiciousReferral' : IDL.Null,
    'suspiciousAdClicks' : IDL.Null,
    'referralLoop' : IDL.Null,
    'manualFlag' : IDL.Null,
    'multipleAccounts' : IDL.Null,
    'earlyWithdrawal' : IDL.Null,
  });
  const FraudFlagPublic = IDL.Record({
    'userId' : UserId,
    'resolution' : IDL.Opt(FraudResolution),
    'isResolved' : IDL.Bool,
    'evidence' : IDL.Text,
    'flagType' : FraudFlagType,
    'flaggedAt' : Timestamp,
    'resolvedAt' : IDL.Opt(Timestamp),
    'resolvedBy' : IDL.Opt(UserId),
    'reason' : IDL.Text,
  });
  const FraudStats = IDL.Record({
    'mostCommonFlagType' : IDL.Text,
    'unresolvedFlags' : IDL.Nat,
    'totalFlagged' : IDL.Nat,
    'totalCoinsRolledBack' : IDL.Nat,
    'resolvedFlags' : IDL.Nat,
  });
  const AppSettings = IDL.Record({
    'dailyBaseReward' : IDL.Nat,
    'referralsEnabled' : IDL.Bool,
    'tasksEnabled' : IDL.Bool,
    'dailyCoinsGrantCap' : IDL.Nat,
    'modifiedBy' : IDL.Opt(UserId),
    'adsEnabled' : IDL.Bool,
    'maxDailyAdWatches' : IDL.Nat,
    'dailyRewardsEnabled' : IDL.Bool,
    'maxCoinsPerUser' : IDL.Nat,
    'coinsPerAd' : IDL.Nat,
    'lastModified' : Timestamp,
    'streakCap' : IDL.Nat,
    'fraudPenaltyCoins' : IDL.Nat,
    'withdrawalsEnabled' : IDL.Bool,
    'referralBonus' : IDL.Nat,
    'streakMultiplier' : IDL.Nat,
    'minWithdrawalRupees' : IDL.Nat,
  });
  const SettingsChangeLog = IDL.Record({
    'field' : IDL.Text,
    'newVal' : IDL.Text,
    'timestamp' : Timestamp,
    'adminId' : UserId,
    'oldVal' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalCoinsInCirculation' : Coins,
    'totalApprovedWithdrawalsRupees' : IDL.Nat,
    'pendingWithdrawalsCount' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const AnnouncementPublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(Timestamp),
    'urgency' : AnnouncementUrgency,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'isActive' : IDL.Bool,
    'target' : AnnouncementTarget,
    'message' : IDL.Text,
    'scheduledAt' : IDL.Opt(Timestamp),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskCompletion = IDL.Record({
    'completedAt' : Timestamp,
    'userId' : UserId,
    'taskId' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Text,
    'rank' : IDL.Nat,
    'coinsEarned' : IDL.Nat,
  });
  const LeaderboardResult = IDL.Record({
    'userRank' : IDL.Record({
      'username' : IDL.Text,
      'rank' : IDL.Nat,
      'coinsEarned' : IDL.Nat,
    }),
    'entries' : IDL.Vec(LeaderboardEntry),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'coinReward' : Coins,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminAddCoins' : IDL.Func([UserId, Coins, IDL.Text], [], []),
    'adminAddWithdrawalNote' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminBulkApproveWithdrawals' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
        [],
      ),
    'adminBulkBlockUsers' : IDL.Func(
        [IDL.Vec(UserId), IDL.Bool, IDL.Text],
        [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
        [],
      ),
    'adminBulkRejectWithdrawals' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
        [],
      ),
    'adminCreateAnnouncement' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          AnnouncementUrgency,
          AnnouncementTarget,
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
        ],
        [IDL.Nat],
        [],
      ),
    'adminDeductCoins' : IDL.Func([UserId, Coins, IDL.Text], [], []),
    'adminDeleteAnnouncement' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDetectSuspiciousReferralsByTime' : IDL.Func(
        [],
        [IDL.Vec(ReferralRelationshipPublic)],
        ['query'],
      ),
    'adminFlagUser' : IDL.Func(
        [UserId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllReferrals' : IDL.Func(
        [],
        [IDL.Vec(ReferralRelationshipPublic)],
        ['query'],
      ),
    'adminGetAllTransactions' : IDL.Func(
        [
          IDL.Opt(UserId),
          IDL.Opt(TransactionMethod),
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          IDL.Nat,
          IDL.Nat,
        ],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'transactions' : IDL.Vec(Transaction),
          }),
        ],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserAdminDetail)], ['query']),
    'adminGetAllWithdrawals' : IDL.Func(
        [
          IDL.Opt(WithdrawalStatus),
          IDL.Opt(UserId),
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(WithdrawalRequestPublic)],
        ['query'],
      ),
    'adminGetEnhancedStats' : IDL.Func([], [EnhancedAdminStats], ['query']),
    'adminGetFlaggedUsers' : IDL.Func(
        [],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'adminGetFraudFlags' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(FraudFlagPublic)],
        ['query'],
      ),
    'adminGetFraudStats' : IDL.Func([], [FraudStats], ['query']),
    'adminGetSettings' : IDL.Func([], [AppSettings], ['query']),
    'adminGetSettingsChangeLog' : IDL.Func(
        [],
        [IDL.Vec(SettingsChangeLog)],
        ['query'],
      ),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'adminGetUserDetail' : IDL.Func(
        [UserId],
        [IDL.Opt(UserAdminDetail)],
        ['query'],
      ),
    'adminGetUserReferralChain' : IDL.Func(
        [UserId],
        [
          IDL.Record({
            'referred' : IDL.Vec(UserProfilePublic),
            'referredBy' : IDL.Opt(UserProfilePublic),
          }),
        ],
        ['query'],
      ),
    'adminListAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(AnnouncementPublic)],
        ['query'],
      ),
    'adminMarkWithdrawalPaid' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminRejectWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminResolveFraudFlag' : IDL.Func(
        [UserId, FraudFlagType, FraudResolution],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRevokeReferral' : IDL.Func(
        [UserId, UserId, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminToggleBlock' : IDL.Func([UserId, IDL.Bool, IDL.Text], [], []),
    'adminUpdateAnnouncement' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          AnnouncementUrgency,
          AnnouncementTarget,
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateSettings' : IDL.Func(
        [AppSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'applyReferralCode' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyReward' : IDL.Func([IDL.Opt(IDL.Text)], [Coins], []),
    'completeTask' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [Coins], []),
    'dismissAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveAnnouncements' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(AnnouncementPublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([IDL.Opt(IDL.Text)], [Coins], ['query']),
    'getMyCompletedTasks' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(TaskCompletion)],
        ['query'],
      ),
    'getMyMobileStatus' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'mobileNumber' : IDL.Opt(IDL.Text),
            'mobileVerified' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getMyProfile' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getMyReferralCode' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
    'getMyWithdrawals' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(WithdrawalRequestPublic)],
        ['query'],
      ),
    'getRupeeBalance' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Nat], ['query']),
    'getSessionPrincipal' : IDL.Func([IDL.Text], [IDL.Opt(UserId)], ['query']),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getTopEarners' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [LeaderboardResult],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'transactions' : IDL.Vec(Transaction),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [UserId, IDL.Opt(IDL.Text)],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'loginWithMobileOTP' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'isNewUser' : IDL.Bool,
              'sessionToken' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [UserProfilePublic],
        [],
      ),
    'requestMobileOTP' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitWithdrawal' : IDL.Func(
        [
          WithdrawalMethod,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [WithdrawalRequestPublic],
        [],
      ),
    'verifyMobileOTP' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'watchAd' : IDL.Func([IDL.Opt(IDL.Text)], [Coins], []),
  });
};

export const init = ({ IDL }) => { return []; };