/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface LeaderboardEntry {
    username: string;
    userId: string;
    rank: bigint;
    coinsEarned: bigint;
}
export interface FraudFlagPublic {
    userId: UserId;
    resolution?: FraudResolution;
    isResolved: boolean;
    evidence: string;
    flagType: FraudFlagType;
    flaggedAt: Timestamp;
    resolvedAt?: Timestamp;
    resolvedBy?: UserId;
    reason: string;
}
export interface Task {
    id: bigint;
    title: string;
    description: string;
    coinReward: Coins;
    isActive: boolean;
}
export type Coins = bigint;
export interface Transaction {
    id: bigint;
    method: TransactionMethod;
    userId: UserId;
    note: string;
    createdAt: Timestamp;
    isCredit: boolean;
    amount: Coins;
}
export interface DailyEarningEntry {
    date: string;
    rupeesWithdrawn: bigint;
    coinsEarned: bigint;
}
export interface EnhancedAdminStats {
    avgCoinsPerAd: bigint;
    totalCoinsInCirculation: Coins;
    earningsBreakdown: EarningsBreakdown;
    totalApprovedWithdrawalsRupees: bigint;
    pendingWithdrawalsCount: bigint;
    activeUsersThisWeek: bigint;
    dailyEarningsTrend: Array<DailyEarningEntry>;
    totalAdsWatched: bigint;
    totalUsers: bigint;
    totalCoinsEarned: bigint;
    totalRupeesPaidOut: bigint;
}
export interface TaskCompletion {
    completedAt: Timestamp;
    userId: UserId;
    taskId: bigint;
}
export interface AnnouncementPublic {
    id: bigint;
    title: string;
    expiresAt?: Timestamp;
    urgency: AnnouncementUrgency;
    createdAt: Timestamp;
    createdBy: UserId;
    isActive: boolean;
    target: AnnouncementTarget;
    message: string;
    scheduledAt?: Timestamp;
}
export interface LeaderboardResult {
    userRank: {
        username: string;
        rank: bigint;
        coinsEarned: bigint;
    };
    entries: Array<LeaderboardEntry>;
}
export interface BlockAuditEntry {
    blocked: boolean;
    timestamp: Timestamp;
    adminId: UserId;
    reason: string;
}
export interface UserProfilePublic {
    lastLoginDate: Timestamp;
    principal: UserId;
    referralCode: string;
    username: string;
    coinBalance: Coins;
    isBlocked: boolean;
    createdAt: Timestamp;
    mobileNumber?: string;
    mobileVerified: boolean;
    referredBy?: UserId;
    blockHistory: Array<BlockAuditEntry>;
    currentStreak: bigint;
}
export interface SettingsChangeLog {
    field: string;
    newVal: string;
    timestamp: Timestamp;
    adminId: UserId;
    oldVal: string;
}
export interface FraudStats {
    mostCommonFlagType: string;
    unresolvedFlags: bigint;
    totalFlagged: bigint;
    totalCoinsRolledBack: bigint;
    resolvedFlags: bigint;
}
export type UserId = Principal;
export interface UserAdminDetail {
    totalWithdrawnRupees: bigint;
    fraudFlagCount: bigint;
    totalCoinsEarned: Coins;
    profile: UserProfilePublic;
}
export interface WithdrawalRequestPublic {
    id: bigint;
    status: WithdrawalStatus;
    method: WithdrawalMethod;
    userId: UserId;
    createdAt: Timestamp;
    paymentDetails?: string;
    adminNote: string;
    rupeeAmount: bigint;
    details: string;
    paidAt?: Timestamp;
    coinsDeducted: Coins;
    resolvedAt?: Timestamp;
    resolvedBy?: UserId;
}
export interface ReferralRelationshipPublic {
    status: ReferralStatus;
    refereeId: UserId;
    referrerId: UserId;
    timestamp: Timestamp;
    revokeReason?: string;
    bonusGiven: Coins;
}
export interface EarningsBreakdown {
    fromAds: bigint;
    fromDaily: bigint;
    fromReferral: bigint;
    fromTasks: bigint;
    fromAdmin: bigint;
}
export interface AppSettings {
    dailyBaseReward: bigint;
    referralsEnabled: boolean;
    tasksEnabled: boolean;
    dailyCoinsGrantCap: bigint;
    modifiedBy?: UserId;
    adsEnabled: boolean;
    maxDailyAdWatches: bigint;
    dailyRewardsEnabled: boolean;
    maxCoinsPerUser: bigint;
    coinsPerAd: bigint;
    lastModified: Timestamp;
    streakCap: bigint;
    fraudPenaltyCoins: bigint;
    withdrawalsEnabled: boolean;
    referralBonus: bigint;
    streakMultiplier: bigint;
    minWithdrawalRupees: bigint;
}
export interface AdminStats {
    totalCoinsInCirculation: Coins;
    totalApprovedWithdrawalsRupees: bigint;
    pendingWithdrawalsCount: bigint;
    totalUsers: bigint;
}
export enum AnnouncementTarget {
    all = "all",
    adminsOnly = "adminsOnly",
    newUsers = "newUsers",
    inactiveUsers = "inactiveUsers"
}
export enum AnnouncementUrgency {
    warning = "warning",
    info = "info",
    urgent = "urgent"
}
export enum FraudFlagType {
    suspiciousReferral = "suspiciousReferral",
    suspiciousAdClicks = "suspiciousAdClicks",
    referralLoop = "referralLoop",
    manualFlag = "manualFlag",
    multipleAccounts = "multipleAccounts",
    earlyWithdrawal = "earlyWithdrawal"
}
export enum FraudResolution {
    blockUser = "blockUser",
    dismiss = "dismiss",
    markLegitimate = "markLegitimate"
}
export enum ReferralStatus {
    active = "active",
    revoked = "revoked",
    flagged = "flagged"
}
export enum TransactionMethod {
    ad = "ad",
    referral = "referral",
    admin = "admin",
    task = "task",
    withdrawal = "withdrawal",
    daily = "daily"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalMethod {
    upi = "upi",
    bank = "bank",
    paytm = "paytm"
}
export enum WithdrawalStatus {
    pending = "pending",
    paid = "paid",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    adminAddCoins(userId: UserId, amount: Coins, note: string): Promise<void>;
    adminAddWithdrawalNote(requestId: bigint, note: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminApproveWithdrawal(requestId: bigint, note: string): Promise<void>;
    adminBulkApproveWithdrawals(requestIds: Array<bigint>, note: string): Promise<{
        failed: bigint;
        succeeded: bigint;
    }>;
    adminBulkBlockUsers(userIds: Array<UserId>, blocked: boolean, reason: string): Promise<{
        failed: bigint;
        succeeded: bigint;
    }>;
    adminBulkRejectWithdrawals(requestIds: Array<bigint>, reason: string): Promise<{
        failed: bigint;
        succeeded: bigint;
    }>;
    adminCreateAnnouncement(title: string, message: string, urgency: AnnouncementUrgency, target: AnnouncementTarget, scheduledAt: Timestamp | null, expiresAt: Timestamp | null): Promise<bigint>;
    adminDeductCoins(userId: UserId, amount: Coins, reason: string): Promise<void>;
    adminDeleteAnnouncement(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDetectSuspiciousReferralsByTime(): Promise<Array<ReferralRelationshipPublic>>;
    adminFlagUser(userId: UserId, reason: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllReferrals(): Promise<Array<ReferralRelationshipPublic>>;
    adminGetAllTransactions(userId: UserId | null, method: TransactionMethod | null, fromDate: Timestamp | null, toDate: Timestamp | null, limit: bigint, offset: bigint): Promise<{
        total: bigint;
        transactions: Array<Transaction>;
    }>;
    adminGetAllUsers(): Promise<Array<UserAdminDetail>>;
    adminGetAllWithdrawals(statusFilter: WithdrawalStatus | null, userIdFilter: UserId | null, fromDate: Timestamp | null, toDate: Timestamp | null, minRupees: bigint | null, maxRupees: bigint | null): Promise<Array<WithdrawalRequestPublic>>;
    adminGetEnhancedStats(): Promise<EnhancedAdminStats>;
    adminGetFlaggedUsers(): Promise<Array<UserProfilePublic>>;
    adminGetFraudFlags(unresolvedOnly: boolean): Promise<Array<FraudFlagPublic>>;
    adminGetFraudStats(): Promise<FraudStats>;
    adminGetSettings(): Promise<AppSettings>;
    adminGetSettingsChangeLog(): Promise<Array<SettingsChangeLog>>;
    adminGetStats(): Promise<AdminStats>;
    adminGetUserDetail(userId: UserId): Promise<UserAdminDetail | null>;
    adminGetUserReferralChain(userId: UserId): Promise<{
        referred: Array<UserProfilePublic>;
        referredBy?: UserProfilePublic;
    }>;
    adminListAnnouncements(): Promise<Array<AnnouncementPublic>>;
    adminMarkWithdrawalPaid(id: bigint, paymentRef: string): Promise<void>;
    adminRejectWithdrawal(requestId: bigint, adminNote: string): Promise<void>;
    adminResolveFraudFlag(userId: UserId, flagType: FraudFlagType, resolution: FraudResolution): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRevokeReferral(referrerId: UserId, refereeId: UserId, reason: string, deductBonus: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminToggleBlock(userId: UserId, blocked: boolean, reason: string): Promise<void>;
    adminUpdateAnnouncement(id: bigint, title: string, message: string, urgency: AnnouncementUrgency, target: AnnouncementTarget, scheduledAt: Timestamp | null, expiresAt: Timestamp | null, isActive: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateSettings(next: AppSettings): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    applyReferralCode(code: string, sessionToken: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimDailyReward(sessionToken: string | null): Promise<Coins>;
    completeTask(taskId: bigint, sessionToken: string | null): Promise<Coins>;
    dismissAnnouncement(id: bigint, sessionToken: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveAnnouncements(sessionToken: string | null): Promise<Array<AnnouncementPublic>>;
    getCallerUserRole(): Promise<UserRole>;
    getCoinBalance(sessionToken: string | null): Promise<Coins>;
    getMyCompletedTasks(sessionToken: string | null): Promise<Array<TaskCompletion>>;
    getMyMobileStatus(sessionToken: string | null): Promise<{
        mobileNumber?: string;
        mobileVerified: boolean;
    }>;
    getMyProfile(sessionToken: string | null): Promise<UserProfilePublic | null>;
    getMyReferralCode(sessionToken: string | null): Promise<string>;
    getMyWithdrawals(sessionToken: string | null): Promise<Array<WithdrawalRequestPublic>>;
    getRupeeBalance(sessionToken: string | null): Promise<bigint>;
    getSessionPrincipal(token: string): Promise<UserId | null>;
    getSettings(): Promise<AppSettings>;
    getTopEarners(period: string, limit: bigint, sessionToken: string | null): Promise<LeaderboardResult>;
    getTransactionHistory(limit: bigint, offset: bigint, sessionToken: string | null): Promise<{
        total: bigint;
        transactions: Array<Transaction>;
    }>;
    getUserProfile(userId: UserId, sessionToken: string | null): Promise<UserProfilePublic | null>;
    isCallerAdmin(): Promise<boolean>;
    listTasks(): Promise<Array<Task>>;
    loginWithMobileOTP(mobileNumber: string, otpCode: string): Promise<{
        __kind__: "ok";
        ok: {
            isNewUser: boolean;
            sessionToken: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(username: string, sessionToken: string | null): Promise<UserProfilePublic>;
    requestMobileOTP(mobileNumber: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitWithdrawal(method: WithdrawalMethod, details: string, rupeeAmount: bigint, paymentDetails: string | null, sessionToken: string | null): Promise<WithdrawalRequestPublic>;
    verifyMobileOTP(mobileNumber: string, otpCode: string, sessionToken: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    watchAd(sessionToken: string | null): Promise<Coins>;
}
import type { AnnouncementPublic as _AnnouncementPublic, AnnouncementTarget as _AnnouncementTarget, AnnouncementUrgency as _AnnouncementUrgency, AppSettings as _AppSettings, BlockAuditEntry as _BlockAuditEntry, Coins as _Coins, FraudFlagPublic as _FraudFlagPublic, FraudFlagType as _FraudFlagType, FraudResolution as _FraudResolution, ReferralRelationshipPublic as _ReferralRelationshipPublic, ReferralStatus as _ReferralStatus, Timestamp as _Timestamp, Transaction as _Transaction, TransactionMethod as _TransactionMethod, UserAdminDetail as _UserAdminDetail, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, WithdrawalMethod as _WithdrawalMethod, WithdrawalRequestPublic as _WithdrawalRequestPublic, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminAddCoins(arg0: UserId, arg1: Coins, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCoins(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCoins(arg0, arg1, arg2);
            return result;
        }
    }
    async adminAddWithdrawalNote(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddWithdrawalNote(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddWithdrawalNote(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminApproveWithdrawal(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveWithdrawal(arg0, arg1);
            return result;
        }
    }
    async adminBulkApproveWithdrawals(arg0: Array<bigint>, arg1: string): Promise<{
        failed: bigint;
        succeeded: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBulkApproveWithdrawals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBulkApproveWithdrawals(arg0, arg1);
            return result;
        }
    }
    async adminBulkBlockUsers(arg0: Array<UserId>, arg1: boolean, arg2: string): Promise<{
        failed: bigint;
        succeeded: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBulkBlockUsers(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBulkBlockUsers(arg0, arg1, arg2);
            return result;
        }
    }
    async adminBulkRejectWithdrawals(arg0: Array<bigint>, arg1: string): Promise<{
        failed: bigint;
        succeeded: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBulkRejectWithdrawals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBulkRejectWithdrawals(arg0, arg1);
            return result;
        }
    }
    async adminCreateAnnouncement(arg0: string, arg1: string, arg2: AnnouncementUrgency, arg3: AnnouncementTarget, arg4: Timestamp | null, arg5: Timestamp | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateAnnouncement(arg0, arg1, to_candid_AnnouncementUrgency_n2(this._uploadFile, this._downloadFile, arg2), to_candid_AnnouncementTarget_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateAnnouncement(arg0, arg1, to_candid_AnnouncementUrgency_n2(this._uploadFile, this._downloadFile, arg2), to_candid_AnnouncementTarget_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async adminDeductCoins(arg0: UserId, arg1: Coins, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeductCoins(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeductCoins(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeleteAnnouncement(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteAnnouncement(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteAnnouncement(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDetectSuspiciousReferralsByTime(): Promise<Array<ReferralRelationshipPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDetectSuspiciousReferralsByTime();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDetectSuspiciousReferralsByTime();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminFlagUser(arg0: UserId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminFlagUser(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminFlagUser(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllReferrals(): Promise<Array<ReferralRelationshipPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllReferrals();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllReferrals();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllTransactions(arg0: UserId | null, arg1: TransactionMethod | null, arg2: Timestamp | null, arg3: Timestamp | null, arg4: bigint, arg5: bigint): Promise<{
        total: bigint;
        transactions: Array<Transaction>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUsers(): Promise<Array<UserAdminDetail>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllWithdrawals(arg0: WithdrawalStatus | null, arg1: UserId | null, arg2: Timestamp | null, arg3: Timestamp | null, arg4: bigint | null, arg5: bigint | null): Promise<Array<WithdrawalRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllWithdrawals(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllWithdrawals(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetEnhancedStats(): Promise<EnhancedAdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetEnhancedStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetEnhancedStats();
            return result;
        }
    }
    async adminGetFlaggedUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFlaggedUsers();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFlaggedUsers();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetFraudFlags(arg0: boolean): Promise<Array<FraudFlagPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFraudFlags(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFraudFlags(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetFraudStats(): Promise<FraudStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFraudStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFraudStats();
            return result;
        }
    }
    async adminGetSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSettings();
                return from_candid_AppSettings_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSettings();
            return from_candid_AppSettings_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetSettingsChangeLog(): Promise<Array<SettingsChangeLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSettingsChangeLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSettingsChangeLog();
            return result;
        }
    }
    async adminGetStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return result;
        }
    }
    async adminGetUserDetail(arg0: UserId): Promise<UserAdminDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserDetail(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserDetail(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserReferralChain(arg0: UserId): Promise<{
        referred: Array<UserProfilePublic>;
        referredBy?: UserProfilePublic;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserReferralChain(arg0);
                return from_candid_record_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserReferralChain(arg0);
            return from_candid_record_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListAnnouncements(): Promise<Array<AnnouncementPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAnnouncements();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAnnouncements();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminMarkWithdrawalPaid(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMarkWithdrawalPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMarkWithdrawalPaid(arg0, arg1);
            return result;
        }
    }
    async adminRejectWithdrawal(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectWithdrawal(arg0, arg1);
            return result;
        }
    }
    async adminResolveFraudFlag(arg0: UserId, arg1: FraudFlagType, arg2: FraudResolution): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResolveFraudFlag(arg0, to_candid_FraudFlagType_n62(this._uploadFile, this._downloadFile, arg1), to_candid_FraudResolution_n64(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResolveFraudFlag(arg0, to_candid_FraudFlagType_n62(this._uploadFile, this._downloadFile, arg1), to_candid_FraudResolution_n64(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRevokeReferral(arg0: UserId, arg1: UserId, arg2: string, arg3: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRevokeReferral(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRevokeReferral(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminToggleBlock(arg0: UserId, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminToggleBlock(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminToggleBlock(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUpdateAnnouncement(arg0: bigint, arg1: string, arg2: string, arg3: AnnouncementUrgency, arg4: AnnouncementTarget, arg5: Timestamp | null, arg6: Timestamp | null, arg7: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateAnnouncement(arg0, arg1, arg2, to_candid_AnnouncementUrgency_n2(this._uploadFile, this._downloadFile, arg3), to_candid_AnnouncementTarget_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateAnnouncement(arg0, arg1, arg2, to_candid_AnnouncementUrgency_n2(this._uploadFile, this._downloadFile, arg3), to_candid_AnnouncementTarget_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateSettings(arg0: AppSettings): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateSettings(to_candid_AppSettings_n66(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateSettings(to_candid_AppSettings_n66(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyReferralCode(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyReferralCode(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyReferralCode(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n69(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n69(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimDailyReward(arg0: string | null): Promise<Coins> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyReward(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyReward(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async completeTask(arg0: bigint, arg1: string | null): Promise<Coins> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async dismissAnnouncement(arg0: bigint, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissAnnouncement(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissAnnouncement(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveAnnouncements(arg0: string | null): Promise<Array<AnnouncementPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncements(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncements(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinBalance(arg0: string | null): Promise<Coins> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMyCompletedTasks(arg0: string | null): Promise<Array<TaskCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCompletedTasks(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCompletedTasks(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMyMobileStatus(arg0: string | null): Promise<{
        mobileNumber?: string;
        mobileVerified: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMobileStatus(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMobileStatus(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(arg0: string | null): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReferralCode(arg0: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferralCode(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferralCode(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMyWithdrawals(arg0: string | null): Promise<Array<WithdrawalRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWithdrawals(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWithdrawals(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRupeeBalance(arg0: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRupeeBalance(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRupeeBalance(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getSessionPrincipal(arg0: string): Promise<UserId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionPrincipal(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionPrincipal(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_AppSettings_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_AppSettings_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopEarners(arg0: string, arg1: bigint, arg2: string | null): Promise<LeaderboardResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopEarners(arg0, arg1, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopEarners(arg0, arg1, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getTransactionHistory(arg0: bigint, arg1: bigint, arg2: string | null): Promise<{
        total: bigint;
        transactions: Array<Transaction>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0, arg1, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0, arg1, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId, arg1: string | null): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasks();
            return result;
        }
    }
    async loginWithMobileOTP(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            isNewUser: boolean;
            sessionToken: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithMobileOTP(arg0, arg1);
                return from_candid_variant_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithMobileOTP(arg0, arg1);
            return from_candid_variant_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string | null): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfilePublic_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfilePublic_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestMobileOTP(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestMobileOTP(arg0);
                return from_candid_variant_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestMobileOTP(arg0);
            return from_candid_variant_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitWithdrawal(arg0: WithdrawalMethod, arg1: string, arg2: bigint, arg3: string | null, arg4: string | null): Promise<WithdrawalRequestPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawal(to_candid_WithdrawalMethod_n76(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg4));
                return from_candid_WithdrawalRequestPublic_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawal(to_candid_WithdrawalMethod_n76(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg4));
            return from_candid_WithdrawalRequestPublic_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyMobileOTP(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMobileOTP(arg0, arg1, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMobileOTP(arg0, arg1, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async watchAd(arg0: string | null): Promise<Coins> {
        if (this.processError) {
            try {
                const result = await this.actor.watchAd(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.watchAd(to_candid_opt_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AnnouncementPublic_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementPublic): AnnouncementPublic {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_AnnouncementTarget_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementTarget): AnnouncementTarget {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_AnnouncementUrgency_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementUrgency): AnnouncementUrgency {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_AppSettings_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppSettings): AppSettings {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_FraudFlagPublic_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FraudFlagPublic): FraudFlagPublic {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_FraudFlagType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FraudFlagType): FraudFlagType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_FraudResolution_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FraudResolution): FraudResolution {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_ReferralRelationshipPublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferralRelationshipPublic): ReferralRelationshipPublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ReferralStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferralStatus): ReferralStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionMethod_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionMethod): TransactionMethod {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserAdminDetail_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAdminDetail): UserAdminDetail {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalMethod_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalMethod): WithdrawalMethod {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequestPublic_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequestPublic): WithdrawalRequestPublic {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FraudResolution]): FraudResolution | null {
    return value.length === 0 ? null : from_candid_FraudResolution_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserAdminDetail]): UserAdminDetail | null {
    return value.length === 0 ? null : from_candid_UserAdminDetail_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    transactions: Array<_Transaction>;
}): {
    total: bigint;
    transactions: Array<Transaction>;
} {
    return {
        total: value.total,
        transactions: from_candid_vec_n18(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    method: _TransactionMethod;
    userId: _UserId;
    note: string;
    createdAt: _Timestamp;
    isCredit: boolean;
    amount: _Coins;
}): {
    id: bigint;
    method: TransactionMethod;
    userId: UserId;
    note: string;
    createdAt: Timestamp;
    isCredit: boolean;
    amount: Coins;
} {
    return {
        id: value.id,
        method: from_candid_TransactionMethod_n21(_uploadFile, _downloadFile, value.method),
        userId: value.userId,
        note: value.note,
        createdAt: value.createdAt,
        isCredit: value.isCredit,
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalWithdrawnRupees: bigint;
    fraudFlagCount: bigint;
    totalCoinsEarned: _Coins;
    profile: _UserProfilePublic;
}): {
    totalWithdrawnRupees: bigint;
    fraudFlagCount: bigint;
    totalCoinsEarned: Coins;
    profile: UserProfilePublic;
} {
    return {
        totalWithdrawnRupees: value.totalWithdrawnRupees,
        fraudFlagCount: value.fraudFlagCount,
        totalCoinsEarned: value.totalCoinsEarned,
        profile: from_candid_UserProfilePublic_n26(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastLoginDate: _Timestamp;
    principal: _UserId;
    referralCode: string;
    username: string;
    coinBalance: _Coins;
    isBlocked: boolean;
    createdAt: _Timestamp;
    mobileNumber: [] | [string];
    mobileVerified: boolean;
    referredBy: [] | [_UserId];
    blockHistory: Array<_BlockAuditEntry>;
    currentStreak: bigint;
}): {
    lastLoginDate: Timestamp;
    principal: UserId;
    referralCode: string;
    username: string;
    coinBalance: Coins;
    isBlocked: boolean;
    createdAt: Timestamp;
    mobileNumber?: string;
    mobileVerified: boolean;
    referredBy?: UserId;
    blockHistory: Array<BlockAuditEntry>;
    currentStreak: bigint;
} {
    return {
        lastLoginDate: value.lastLoginDate,
        principal: value.principal,
        referralCode: value.referralCode,
        username: value.username,
        coinBalance: value.coinBalance,
        isBlocked: value.isBlocked,
        createdAt: value.createdAt,
        mobileNumber: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.mobileNumber)),
        mobileVerified: value.mobileVerified,
        referredBy: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.referredBy)),
        blockHistory: value.blockHistory,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    method: _WithdrawalMethod;
    userId: _UserId;
    createdAt: _Timestamp;
    paymentDetails: [] | [string];
    adminNote: string;
    rupeeAmount: bigint;
    details: string;
    paidAt: [] | [_Timestamp];
    coinsDeducted: _Coins;
    resolvedAt: [] | [_Timestamp];
    resolvedBy: [] | [_UserId];
}): {
    id: bigint;
    status: WithdrawalStatus;
    method: WithdrawalMethod;
    userId: UserId;
    createdAt: Timestamp;
    paymentDetails?: string;
    adminNote: string;
    rupeeAmount: bigint;
    details: string;
    paidAt?: Timestamp;
    coinsDeducted: Coins;
    resolvedAt?: Timestamp;
    resolvedBy?: UserId;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n36(_uploadFile, _downloadFile, value.status),
        method: from_candid_WithdrawalMethod_n38(_uploadFile, _downloadFile, value.method),
        userId: value.userId,
        createdAt: value.createdAt,
        paymentDetails: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.paymentDetails)),
        adminNote: value.adminNote,
        rupeeAmount: value.rupeeAmount,
        details: value.details,
        paidAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.paidAt)),
        coinsDeducted: value.coinsDeducted,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.resolvedAt)),
        resolvedBy: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.resolvedBy))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    resolution: [] | [_FraudResolution];
    isResolved: boolean;
    evidence: string;
    flagType: _FraudFlagType;
    flaggedAt: _Timestamp;
    resolvedAt: [] | [_Timestamp];
    resolvedBy: [] | [_UserId];
    reason: string;
}): {
    userId: UserId;
    resolution?: FraudResolution;
    isResolved: boolean;
    evidence: string;
    flagType: FraudFlagType;
    flaggedAt: Timestamp;
    resolvedAt?: Timestamp;
    resolvedBy?: UserId;
    reason: string;
} {
    return {
        userId: value.userId,
        resolution: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.resolution)),
        isResolved: value.isResolved,
        evidence: value.evidence,
        flagType: from_candid_FraudFlagType_n48(_uploadFile, _downloadFile, value.flagType),
        flaggedAt: value.flaggedAt,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.resolvedAt)),
        resolvedBy: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.resolvedBy)),
        reason: value.reason
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyBaseReward: bigint;
    referralsEnabled: boolean;
    tasksEnabled: boolean;
    dailyCoinsGrantCap: bigint;
    modifiedBy: [] | [_UserId];
    adsEnabled: boolean;
    maxDailyAdWatches: bigint;
    dailyRewardsEnabled: boolean;
    maxCoinsPerUser: bigint;
    coinsPerAd: bigint;
    lastModified: _Timestamp;
    streakCap: bigint;
    fraudPenaltyCoins: bigint;
    withdrawalsEnabled: boolean;
    referralBonus: bigint;
    streakMultiplier: bigint;
    minWithdrawalRupees: bigint;
}): {
    dailyBaseReward: bigint;
    referralsEnabled: boolean;
    tasksEnabled: boolean;
    dailyCoinsGrantCap: bigint;
    modifiedBy?: UserId;
    adsEnabled: boolean;
    maxDailyAdWatches: bigint;
    dailyRewardsEnabled: boolean;
    maxCoinsPerUser: bigint;
    coinsPerAd: bigint;
    lastModified: Timestamp;
    streakCap: bigint;
    fraudPenaltyCoins: bigint;
    withdrawalsEnabled: boolean;
    referralBonus: bigint;
    streakMultiplier: bigint;
    minWithdrawalRupees: bigint;
} {
    return {
        dailyBaseReward: value.dailyBaseReward,
        referralsEnabled: value.referralsEnabled,
        tasksEnabled: value.tasksEnabled,
        dailyCoinsGrantCap: value.dailyCoinsGrantCap,
        modifiedBy: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.modifiedBy)),
        adsEnabled: value.adsEnabled,
        maxDailyAdWatches: value.maxDailyAdWatches,
        dailyRewardsEnabled: value.dailyRewardsEnabled,
        maxCoinsPerUser: value.maxCoinsPerUser,
        coinsPerAd: value.coinsPerAd,
        lastModified: value.lastModified,
        streakCap: value.streakCap,
        fraudPenaltyCoins: value.fraudPenaltyCoins,
        withdrawalsEnabled: value.withdrawalsEnabled,
        referralBonus: value.referralBonus,
        streakMultiplier: value.streakMultiplier,
        minWithdrawalRupees: value.minWithdrawalRupees
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referred: Array<_UserProfilePublic>;
    referredBy: [] | [_UserProfilePublic];
}): {
    referred: Array<UserProfilePublic>;
    referredBy?: UserProfilePublic;
} {
    return {
        referred: from_candid_vec_n41(_uploadFile, _downloadFile, value.referred),
        referredBy: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.referredBy))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    expiresAt: [] | [_Timestamp];
    urgency: _AnnouncementUrgency;
    createdAt: _Timestamp;
    createdBy: _UserId;
    isActive: boolean;
    target: _AnnouncementTarget;
    message: string;
    scheduledAt: [] | [_Timestamp];
}): {
    id: bigint;
    title: string;
    expiresAt?: Timestamp;
    urgency: AnnouncementUrgency;
    createdAt: Timestamp;
    createdBy: UserId;
    isActive: boolean;
    target: AnnouncementTarget;
    message: string;
    scheduledAt?: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        expiresAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.expiresAt)),
        urgency: from_candid_AnnouncementUrgency_n58(_uploadFile, _downloadFile, value.urgency),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        isActive: value.isActive,
        target: from_candid_AnnouncementTarget_n60(_uploadFile, _downloadFile, value.target),
        message: value.message,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mobileNumber: [] | [string];
    mobileVerified: boolean;
}): {
    mobileNumber?: string;
    mobileVerified: boolean;
} {
    return {
        mobileNumber: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.mobileNumber)),
        mobileVerified: value.mobileVerified
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReferralStatus;
    refereeId: _UserId;
    referrerId: _UserId;
    timestamp: _Timestamp;
    revokeReason: [] | [string];
    bonusGiven: _Coins;
}): {
    status: ReferralStatus;
    refereeId: UserId;
    referrerId: UserId;
    timestamp: Timestamp;
    revokeReason?: string;
    bonusGiven: Coins;
} {
    return {
        status: from_candid_ReferralStatus_n10(_uploadFile, _downloadFile, value.status),
        refereeId: value.refereeId,
        referrerId: value.referrerId,
        timestamp: value.timestamp,
        revokeReason: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.revokeReason)),
        bonusGiven: value.bonusGiven
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    revoked: null;
} | {
    flagged: null;
}): ReferralStatus {
    return "active" in value ? ReferralStatus.active : "revoked" in value ? ReferralStatus.revoked : "flagged" in value ? ReferralStatus.flagged : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ad: null;
} | {
    referral: null;
} | {
    admin: null;
} | {
    task: null;
} | {
    withdrawal: null;
} | {
    daily: null;
}): TransactionMethod {
    return "ad" in value ? TransactionMethod.ad : "referral" in value ? TransactionMethod.referral : "admin" in value ? TransactionMethod.admin : "task" in value ? TransactionMethod.task : "withdrawal" in value ? TransactionMethod.withdrawal : "daily" in value ? TransactionMethod.daily : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "paid" in value ? WithdrawalStatus.paid : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    bank: null;
} | {
    paytm: null;
}): WithdrawalMethod {
    return "upi" in value ? WithdrawalMethod.upi : "bank" in value ? WithdrawalMethod.bank : "paytm" in value ? WithdrawalMethod.paytm : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blockUser: null;
} | {
    dismiss: null;
} | {
    markLegitimate: null;
}): FraudResolution {
    return "blockUser" in value ? FraudResolution.blockUser : "dismiss" in value ? FraudResolution.dismiss : "markLegitimate" in value ? FraudResolution.markLegitimate : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suspiciousReferral: null;
} | {
    suspiciousAdClicks: null;
} | {
    referralLoop: null;
} | {
    manualFlag: null;
} | {
    multipleAccounts: null;
} | {
    earlyWithdrawal: null;
}): FraudFlagType {
    return "suspiciousReferral" in value ? FraudFlagType.suspiciousReferral : "suspiciousAdClicks" in value ? FraudFlagType.suspiciousAdClicks : "referralLoop" in value ? FraudFlagType.referralLoop : "manualFlag" in value ? FraudFlagType.manualFlag : "multipleAccounts" in value ? FraudFlagType.multipleAccounts : "earlyWithdrawal" in value ? FraudFlagType.earlyWithdrawal : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    urgent: null;
}): AnnouncementUrgency {
    return "warning" in value ? AnnouncementUrgency.warning : "info" in value ? AnnouncementUrgency.info : "urgent" in value ? AnnouncementUrgency.urgent : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    adminsOnly: null;
} | {
    newUsers: null;
} | {
    inactiveUsers: null;
}): AnnouncementTarget {
    return "all" in value ? AnnouncementTarget.all : "adminsOnly" in value ? AnnouncementTarget.adminsOnly : "newUsers" in value ? AnnouncementTarget.newUsers : "inactiveUsers" in value ? AnnouncementTarget.inactiveUsers : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        isNewUser: boolean;
        sessionToken: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        isNewUser: boolean;
        sessionToken: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAdminDetail>): Array<UserAdminDetail> {
    return value.map((x)=>from_candid_UserAdminDetail_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequestPublic>): Array<WithdrawalRequestPublic> {
    return value.map((x)=>from_candid_WithdrawalRequestPublic_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FraudFlagPublic>): Array<FraudFlagPublic> {
    return value.map((x)=>from_candid_FraudFlagPublic_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnnouncementPublic>): Array<AnnouncementPublic> {
    return value.map((x)=>from_candid_AnnouncementPublic_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReferralRelationshipPublic>): Array<ReferralRelationshipPublic> {
    return value.map((x)=>from_candid_ReferralRelationshipPublic_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementTarget_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementTarget): _AnnouncementTarget {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_AnnouncementUrgency_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementUrgency): _AnnouncementUrgency {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_AppSettings_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppSettings): _AppSettings {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_FraudFlagType_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FraudFlagType): _FraudFlagType {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_FraudResolution_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FraudResolution): _FraudResolution {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionMethod_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionMethod): _TransactionMethod {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalMethod_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): _WithdrawalMethod {
    return to_candid_variant_n77(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): _WithdrawalStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionMethod | null): [] | [_TransactionMethod] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionMethod_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus | null): [] | [_WithdrawalStatus] {
    return value === null ? candid_none() : candid_some(to_candid_WithdrawalStatus_n30(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyBaseReward: bigint;
    referralsEnabled: boolean;
    tasksEnabled: boolean;
    dailyCoinsGrantCap: bigint;
    modifiedBy?: UserId;
    adsEnabled: boolean;
    maxDailyAdWatches: bigint;
    dailyRewardsEnabled: boolean;
    maxCoinsPerUser: bigint;
    coinsPerAd: bigint;
    lastModified: Timestamp;
    streakCap: bigint;
    fraudPenaltyCoins: bigint;
    withdrawalsEnabled: boolean;
    referralBonus: bigint;
    streakMultiplier: bigint;
    minWithdrawalRupees: bigint;
}): {
    dailyBaseReward: bigint;
    referralsEnabled: boolean;
    tasksEnabled: boolean;
    dailyCoinsGrantCap: bigint;
    modifiedBy: [] | [_UserId];
    adsEnabled: boolean;
    maxDailyAdWatches: bigint;
    dailyRewardsEnabled: boolean;
    maxCoinsPerUser: bigint;
    coinsPerAd: bigint;
    lastModified: _Timestamp;
    streakCap: bigint;
    fraudPenaltyCoins: bigint;
    withdrawalsEnabled: boolean;
    referralBonus: bigint;
    streakMultiplier: bigint;
    minWithdrawalRupees: bigint;
} {
    return {
        dailyBaseReward: value.dailyBaseReward,
        referralsEnabled: value.referralsEnabled,
        tasksEnabled: value.tasksEnabled,
        dailyCoinsGrantCap: value.dailyCoinsGrantCap,
        modifiedBy: value.modifiedBy ? candid_some(value.modifiedBy) : candid_none(),
        adsEnabled: value.adsEnabled,
        maxDailyAdWatches: value.maxDailyAdWatches,
        dailyRewardsEnabled: value.dailyRewardsEnabled,
        maxCoinsPerUser: value.maxCoinsPerUser,
        coinsPerAd: value.coinsPerAd,
        lastModified: value.lastModified,
        streakCap: value.streakCap,
        fraudPenaltyCoins: value.fraudPenaltyCoins,
        withdrawalsEnabled: value.withdrawalsEnabled,
        referralBonus: value.referralBonus,
        streakMultiplier: value.streakMultiplier,
        minWithdrawalRupees: value.minWithdrawalRupees
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionMethod): {
    ad: null;
} | {
    referral: null;
} | {
    admin: null;
} | {
    task: null;
} | {
    withdrawal: null;
} | {
    daily: null;
} {
    return value == TransactionMethod.ad ? {
        ad: null
    } : value == TransactionMethod.referral ? {
        referral: null
    } : value == TransactionMethod.admin ? {
        admin: null
    } : value == TransactionMethod.task ? {
        task: null
    } : value == TransactionMethod.withdrawal ? {
        withdrawal: null
    } : value == TransactionMethod.daily ? {
        daily: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementUrgency): {
    warning: null;
} | {
    info: null;
} | {
    urgent: null;
} {
    return value == AnnouncementUrgency.warning ? {
        warning: null
    } : value == AnnouncementUrgency.info ? {
        info: null
    } : value == AnnouncementUrgency.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): {
    pending: null;
} | {
    paid: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == WithdrawalStatus.pending ? {
        pending: null
    } : value == WithdrawalStatus.paid ? {
        paid: null
    } : value == WithdrawalStatus.approved ? {
        approved: null
    } : value == WithdrawalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementTarget): {
    all: null;
} | {
    adminsOnly: null;
} | {
    newUsers: null;
} | {
    inactiveUsers: null;
} {
    return value == AnnouncementTarget.all ? {
        all: null
    } : value == AnnouncementTarget.adminsOnly ? {
        adminsOnly: null
    } : value == AnnouncementTarget.newUsers ? {
        newUsers: null
    } : value == AnnouncementTarget.inactiveUsers ? {
        inactiveUsers: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FraudFlagType): {
    suspiciousReferral: null;
} | {
    suspiciousAdClicks: null;
} | {
    referralLoop: null;
} | {
    manualFlag: null;
} | {
    multipleAccounts: null;
} | {
    earlyWithdrawal: null;
} {
    return value == FraudFlagType.suspiciousReferral ? {
        suspiciousReferral: null
    } : value == FraudFlagType.suspiciousAdClicks ? {
        suspiciousAdClicks: null
    } : value == FraudFlagType.referralLoop ? {
        referralLoop: null
    } : value == FraudFlagType.manualFlag ? {
        manualFlag: null
    } : value == FraudFlagType.multipleAccounts ? {
        multipleAccounts: null
    } : value == FraudFlagType.earlyWithdrawal ? {
        earlyWithdrawal: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FraudResolution): {
    blockUser: null;
} | {
    dismiss: null;
} | {
    markLegitimate: null;
} {
    return value == FraudResolution.blockUser ? {
        blockUser: null
    } : value == FraudResolution.dismiss ? {
        dismiss: null
    } : value == FraudResolution.markLegitimate ? {
        markLegitimate: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): {
    upi: null;
} | {
    bank: null;
} | {
    paytm: null;
} {
    return value == WithdrawalMethod.upi ? {
        upi: null
    } : value == WithdrawalMethod.bank ? {
        bank: null
    } : value == WithdrawalMethod.paytm ? {
        paytm: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
